# Generated by Django 5.0.3 on 2025-09-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baners', '0002_banerheader_link_banerhomepage_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banerheader',
            options={'verbose_name': 'بنر هدر سایت', 'verbose_name_plural': 'بنرهای هدر سایت'},
        ),
        migrations.AlterModelOptions(
            name='banerhomepage',
            options={'verbose_name': 'بنر های صفحه خانه', 'verbose_name_plural': 'بنر های صفحه خانه'},
        ),
    ]
